This is makeindex, version 2.18 [MiKTeX 26.1].
Scanning style file ./manuscrit.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file manuscrit.acn....done (12 entries accepted, 0 rejected).
Sorting entries....done (47 comparisons).
Generating output file manuscrit.acr....done (38 lines written, 0 warnings).
Output written in manuscrit.acr.
Transcript written in manuscrit.alg.
